merge into one script

diff --git a/incus-cluster b/incus-cluster
--- a/incus-cluster
+++ b/incus-cluster
@@ -1,14 +1,86 @@
 #!/usr/bin/env bash
 
-source "$(dirname $0)/incus_source.sh"
+error(){
+    echo "$@" >&2;
+    exit 1;
+}
 
-if [[ "${generate_ansible_inventory}" == "true" && ! -d "${ansible_dir}/inventory" ]]; then
-    error "${ansible_dir} has no 'inventory' directory. Please initialize an ansible project at that path, or set 'generate_ansible_inventory' to false"
+if command -v yq &>/dev/null; then
+    _yq=yq
+elif [ -x './yq' ]; then
+    _yq='./yq'
+else
+    read -p "yq not installed. Do you want to install yq? Press Enter to continue (or type 'n' to skip): " answer
+    if [[ "${answer}" != "n" ]]; then
+        os_type=$(uname -s)
+        if [[ "$os_type" == "Darwin" ]]; then
+            echo "MacOS detected. Install with brew"
+            brew install yq
+        elif [[ "$os_type" == "Linux" ]]; then
+            # Check for Arch Linux
+            if [[ -f /etc/arch-release ]]; then
+                sudo pacman -S yq
+            else
+                echo "This is a (non-Arch) Linux distribution."
+                read -p "Download script and install in /usr/local/bin? (Requires sudo) Press n for local install" global
+                version=`curl https://api.github.com/repos/mikefarah/yq/releases/latest | grep '"tag_name":' | cut -d':' -f2 | sed 's/^.*\"\(.*\)\".*$/\1/g'`
+                if [[ "${global}" != "n" ]]; then
+                    sudo wget https://github.com/mikefarah/yq/releases/download/${version}/yq_linux_amd64 -O /usr/local/bin/yq && \
+                    sudo chmod +x /usr/local/bin/yq
+                else
+                    sudo wget https://github.com/mikefarah/yq/releases/download/${version}/yq_linux_amd64 -O ./yq && \
+                    sudo chmod +x ./yq
+                    _yq='./yq'
+                fi
+            fi
+        else
+            echo "yq not available and OS cannot be detected. Exiting"
+            exit 1;
+        fi
+    else
+        "Do not install. Quitting..."
+        exit 1
+    fi
 fi
+
+config_file=$2
+if [[ -z "${config_file}" ]]; then
+    config_file='./incus.yml'
+fi
+
+if [[ ! -f ${config_file} ]]; then
+    echo "Config file (${config_file}) not found. Quitting…"
+    exit 1
+fi
+
+parseconf(){
+    ${_yq} "${1}" $config_file | sed 's/"\(.*\)"/\1/g'
+}
+
+#variables extracted from incus config file
+project=$(parseconf ".project // \"\"")
+
+if [[ -z "${project}" ]]; then
+    error "'project' config key cannot be empty"
+fi
+
+hosts_num=$(parseconf '.hosts | length')
+
+# Network
+network=$(parseconf ".network.name // \"${project}br0\"")
+network_manage=$(parseconf '.network.manage // true')
+
+# storage
+storage=$(parseconf ".storage.name // \"$project\"")
+storage_manage=$(parseconf '.storage.manage // true')
 
 if ! incus info > /dev/null ; then
     echo "Incus is not properly working. Exiting..."
     exit 1;
+fi
+
+if [[ "${generate_ansible_inventory}" == "true" && ! -d "${ansible_dir}/inventory" ]]; then
+    error "${ansible_dir} has no 'inventory' directory. Please initialize an ansible project at that path, or set 'generate_ansible_inventory' to false"
 fi
 
 #associative array (map)
@@ -22,6 +94,34 @@ if ! incus project show $project  &>/dev/null; then
 fi
 
 incus project switch $project >/dev/null
+
+get_hostvar() {
+    hostname=$(parseconf ".hosts[$f].hostname")
+    quantity=$(parseconf ".hosts[$f].quantity // 1")
+    role=$(parseconf ".hosts[$f].role")
+}
+
+get_name() {
+    if [[ "$hostname" == "null" ]]; then
+        if [[ "$role" == "null" ]]; then
+            error "host #${f} has no hostname nor a role. Quitting…"
+        fi
+        name=$(printf "%s-%02d" "$role" "$i")
+    else
+        if [[ "${qty}" -gt 1 && "$hostname" != *\$*d* ]]; then
+            error "host #${f} has hostname without pattern and quantity > 1. Quitting…"
+        fi
+        name=$(printf "$hostname" "$i")
+    fi
+}
+
+up() {
+image=$(parseconf '.image // "rockylinux/8/cloud"')
+admin_user=$(parseconf '.admin_user  // "admin"')
+generate_ansible_inventory=$(parseconf '.generate_ansible_inventory // false')
+ansible_dir=`realpath $(parseconf '.ansible_dir // "./"')`
+ansible_hosts_file=$(parseconf ".ansible_hosts_file // \"${ansible_dir}/inventory/hosts.ini\"")
+private_key=$(parseconf ".ansible_private_key // \"${ansible_dir}/${project}_key\"")
 
 if [[ "${generate_ansible_inventory}" == "true" ]]; then
     echo "#Generated by $0" > ${ansible_hosts_file}.tmp
@@ -107,37 +207,26 @@ EOF
 
 #foreach hosts_num
 for f in $(seq 0 $((hosts_num - 1))); do
+    get_hostvar
     # parse config file to get host config
-    hostname=$(parseconf ".hosts[$f].hostname")
     memory=$(parseconf ".hosts[$f].memory // 512")
     cpu=$(parseconf ".hosts[$f].cpus // 1")
-    quantity=$(parseconf ".hosts[$f].quantity // 1")
-    role=$(parseconf ".hosts[$f].role")
     root_size=$(parseconf ".hosts[$f].root_size // \"40GB\"")
     if ${_yq} -e ".hosts[$f].groups" ${config_file} &> /dev/null; then
-        mapfile -t gr < <(parseconf ".hosts[$f].groups[] // \"\"" 2>/dev/null)
+        mapfile -t gr < <(parseconf ".hosts[$f].groups[]" 2>/dev/null)
     else
+        if [[ "$role" == "null" ]]; then
+            error "host #${f} has no groups nor role. Quitting…"
+        fi
         gr=("$role")
     fi
-    #echo hostname $hostname mem $memory cpu $cpu quantity $quantity role $role gr $(IFS=','; echo "${gr[*]}"; unset IFS)
-    if [ -z "$role" ]; then
-        error 'memory, cpu, and role are mandatory vars'
-    fi
-    if [[ "$quantity" == "null" ]]; then
-       quantity=1
-    fi
     for i in $(seq 1 $quantity); do
-        if [[ "$hostname" == "null" ]]; then
-            name=$(printf "%s-%02d" "$role" "$i")
-        else
-            name=$(printf "$hostname" "$i")
-        fi
+        get_name
         f_gr=()
         for j in "${!gr[@]}"; do
             f_gr[$j]=$(printf ${gr[$j]} "$i")
         done
         for g in ${f_gr[@]}; do
-            echo "should add '${name}' to groups[$g]"
             #Append host to group multiline string array
             groups[$g]="${groups[$g]}\n$name"
         done;
@@ -217,7 +306,6 @@ if [[ "${generate_ansible_inventory}" == true ]]; then
     echo 'Write finalized ansible hosts.ini file'
     mv ${ansible_hosts_file}.tmp ${ansible_hosts_file}
 fi
-
 echo 'Waiting completion of cloud-init...'
 echo 'If it hangs indefinitely, you might have network issue inside your VMs'
 for name in "${hosts_list[@]}"; do
@@ -226,6 +314,38 @@ for name in "${hosts_list[@]}"; do
     done
     echo "$name is ready"
 done
+}
+
+action() {
+for f in $(seq 0 $((hosts_num - 1))); do
+    # parse config file to get host config
+    get_hostvar
+    #echo hostname $hostname mem $memory cpu $cpu quantity $quantity role $role gr $(IFS=','; echo "${gr[*]}"; unset IFS)
+    for i in $(seq 1 $quantity); do
+        get_name
+        incus $@ $name
+    done
+done
+}
+
+case "$1" in
+    up) up ;;
+    start) action start ;;
+    stop) action stop ;;
+    delete) action delete --force;
+        if [[ "${storage_manage}" == "true" ]]; then
+            incus storage delete $storage
+        fi
+        if [[ "${network_manage}" == "true" ]]; then
+            incus profile device remove default enp5s0
+            incus network delete $network
+        fi
+    ;;
+    *)
+        echo "Usage: $0 {up | start | stop | delete} [config_file]"
+        exit 1
+        ;;
+esac
 
 echo ""
 echo 'Finished successfully!'
